---
title: "Estadística 1 (Probabilidad e Inferencia Estadística)"
---

En esta pestaña encontrarás los resúmenes de los parciales 1, 2, 3 elaborados por mi persona para el curso de Estadística 1. Adicionalmente hallarás los resumenes del cuarto y quinto parcial desarrolados por la *Escuela de Estadística de la Universidad Nacional, Sede Medellín* sobre **Intervalos de Confianza** y **Pruebas de Hipótesis** los cuales están autorizados a ser utilizados durante los exámenes.

### Tablas de la distribución Normal, t y Chi cuadrado

-Para el parcial 2, 3, 4, 5: <a href="Tablas_normal_t_y_ji.pdf#" class="download" title="Tabla de la normal"> Descarga aquí la tabla de la distribución normal </a>

### Tabla de la distribución F

-Para el parcial 5: <a href="tabla_F.pdf#" class="download" title="Tabla de la distribución f"> Descarga aquí la tabla de la distribución F </a>

### Resumen sobre nociones de probabilidad, conjuntos y funciones de probabilidad (Primer parcial)

-Para preparación del parcial 1: <a href="Resumen_primer_parcial.pdf#" class="download" title="Resumen primer parcial"> Descarga aquí el resumen para el primer parcial (NO USABLE EN EL EXAMEN) </a>

### Resumen sobre distribuciones discretas y continuas. (Segundo parcial)

-Para preparación del parcial 2: <a href="Resumen_segundo_parcial.pdf#" class="download" title="Resumen segundo parcial"> Descarga aquí el resumen para el segundo parcial (NO USABLE EN EL EXAMEN) </a>

### Resumen sobre distribuciones bivariadas (Tercer parcial)

### Resumen sobre Intervalos de Confianza. (Cuarto parcial)

-Para el parcial 4: <a href="Resumen_Intervalos_de_confianza.pdf#" class="download" title="Resumen IC"> Descarga aquí el resumen para el cuarto parcial </a>

### Resumen sobre Pruebas de Hipótesis. (Quinto parcial)

-Para el parcial 5: <a href="Resumen_Pruebas_de_hipotesis.pdf#" class="download" title="Resumen PH"> Descarga aquí el resumen para el quinto parcial </a>
